config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new

  get 'tasks/:id', to: 'tasks#show', as: :task

  post 'tasks', to: 'tasks#create'

  # To update a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  # To receive data from form and patch it into db
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def set_task
    @task = Task.find(params[:id])
  end

  def index
    #fetch all tasks
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    # display form for new, and add into dataabase
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)

    redirect_to tasks_path
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    #task = params[:task] # fetching the update details from the form
    # @task = Task.find(params[:id])
    @task.update(task_params)

    # redirect_to '/tasks' + task.id
    redirect_to task_path(@task)
  end

  def destroy
    # task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |form_object| %>
  <div class="form-group">
    <%= form_object.label :title %>
    <%= form_object.text_field :title, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form_object.label :details %>
    <%= form_object.text_field :details, class:'form-control' %>
  </div>

  <% if @task.completed %>
    <div>
        <p><i class="far fa-check-circle"></i>
        Make task uncompleted</p>
    </div>
  <% else %>
    <div>
      <p><i class="far fa-circle"></i>
      Make task completed</p>
    </div>
  <% end %>

  <p></p>
  <%= form_object.submit (@task.new_record? ? 'Add task' : 'Update task'), class: 'btn btn-primary' %>

<% end %>

<p></p>
<i class="fas fa-undo-alt"></i><%= link_to " Back to list", tasks_path %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%=  render 'form' %>

app/views/tasks/index.html.erb
<h1>All tasks</h1>

<div class="container">
  <div class="card-header" style="text-decoration:none">
    <ul class="list-unstyled">
      <% @tasks.each do |t|  %>
        <li>
          <%= check_box_tag 'task_id[]', t.id, t.completed %>
          <% if t.completed %>
            <i class="far fa-check-circle"></i>
          <% else %>
            <i class="far fa-circle"></i>
          <% end %>
          <%= link_to t.title, task_path(t), method: :get %>

          <%= link_to delete_path(t), method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<p></p>

<div>
  <p class="btn btn-warning"><%= link_to "Add a new task", new_path, method: :get %></p>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%=  render 'form' %>

app/views/tasks/show.html.erb
<h1>Task: <%= @task.title %></h1>

<h2 class="task_card"><%= @task.details %></h2>

<% if @task.completed %>
  <div>
      <p><i class="far fa-check-circle"></i>
      This task is completed.</p>
  </div>
<% else %>
  <div>
    <p><i class="far fa-circle"></i>
    This task is not completed yet</p>
  </div>
<% end %>

<%= link_to edit_path, method: :get do %>
  <p class='btn btn-primary'>Edit task</p>
<% end %>

<p></p>
<i class="fas fa-undo-alt"></i><%= link_to " Back to list", tasks_path %>